apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      run: celery
  replicas: 3
  template:
    metadata:
      labels:
        run: celery
    spec:
      containers:
      - name: celery
        image: sneyd321/celery
  
      imagePullSecrets:
        - name: key